[irc]
[irc.libera]
Server="irc.libera.chat:6667"
Nick="MTModsBot"
Password="{{ IRC_LIBERA_PASSWORD }}"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
MessageSplit=true
EditSuffix=" (edited)"
ColorNicks=true
ShowJoinPart=true

[discord]
[discord.mtmods]
Token="{{ DISCORD_MTMODS_TOKEN }}"
Server="905447873402003486"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
AllowMention=["users"]
ShowJoinPart=true

[matrix]
[matrix.mtmods]
Server="https://matrix.org"
Login="@mtmods:matrix.org"
Password="{{ MATRIX_MTMODS_PASSWORD }}"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
NoHomeServerSuffix=true
#HTMLDisable=true

[[gateway]]
name="main-channel"
enable=true
[[gateway.inout]]
account="irc.libera"
channel="#mt-mods"
[[gateway.inout]]
account = "discord.mtmods"
channel="üõ∞modding"
[[gateway.inout]]
account = "matrix.mtmods"
channel="!IuYhGtsAusgKYlpUCs:matrix.org"

[[gateway]]
name="offtopic-channel"
enable=true
[[gateway.inout]]
account="irc.libera"
channel="#mt-mods-offtopic"
[[gateway.inout]]
account = "discord.mtmods"
channel="üèõlounge"
[[gateway.inout]]
account = "matrix.mtmods"
channel="!dQppybfdWYiNSoXjYP:matrix.org"

[[gateway]]
name="review-me-channel"
enable=true
[[gateway.inout]]
account = "discord.mtmods"
channel="pls-review-me"
[[gateway.inout]]
account = "matrix.mtmods"
channel="!OdCHbjfdlIjUXXHqMC:matrix.org"

[[gateway]]
name="tooling-channel"
enable=true
[[gateway.inout]]
account = "discord.mtmods"
channel="üõ†tooling"
[[gateway.inout]]
account = "matrix.mtmods"
channel="!NvhdxpOeVIwUQkaxos:matrix.org"
